server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.107.72.125:8848
    gateway:
      discovery:
        locator:
          enabled: false
      routes: #网关路由配置
        - id: user-service #路由id，自定义，唯一即可
          uri: lb://user-service #路由的目标地址 lb是负载均衡，后面跟服务名称
          predicates: #路由断言，判断请求是否符合路由规则，只有符合规则才将请求转发到目标服务
            - Path=/userService/**  #路由规则，路径断言，按照路径匹配，只要以/orderService/开头就符合路由规则
        - id: log-service
          uri: lb://log-service
          predicates:
            - Path=/logService/**
      globalcors: #全局跨域处理
        add-to-simple-url-handler-mapping: true  #解决option拦截问题
        cors-configurations:
          '[/**]': #拦截哪些跨域请求进行处理，[/**]表示对全部请求做拦截并进行跨域处理
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8081"
              - "http://localhost:8082"
              - "http://localhost:80"
            allowedMethods: # 允许跨域的ajax请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"  #允许在请求头中携带的信息  *表示所有信息都可以携带
            allowedCredentials: true #是否允许携带cookie
            maxAge: 360000  #这次跨域的有效期，有效期内不检测拦截该跨域请求
